# Compile mod tile with its products from the git repo
FROM fedora:33 AS base
RUN dnf install -y git redhat-rpm-config iniparser-devel cairo-devel autoconf automake boost-devel freetype-devel gcc-c++ httpd-devel libicu-devel libtool make mapnik-devel proj-devel

RUN git clone https://github.com/openstreetmap/mod_tile.git && cd mod_tile && \
	./autogen.sh && ./configure && make -j4

FROM fedora:33
#RUN dnf install -y httpd
COPY --from=base /mod_tile/render* /usr/local/bin/
COPY --from=base /mod_tile/examples/config/renderd/renderd.conf.dist /etc/renderd.conf
#COPY --from=base /mod_tile/examples/config/apache2/renderd.conf.dist /etc/httpd/conf.d/renderd.conf

RUN useradd -U renderd
USER renderd

CMD renderd -f
